// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBlog = "blog"

// Blog mapped from table <blog>
type Blog struct {
	ID           int32  `gorm:"column:id;type:INTEGER" json:"id"`
	Title        string `gorm:"column:title;type:TEXT" json:"title"`
	Summary      string `gorm:"column:summary;type:TEXT" json:"summary"`
	Content      string `gorm:"column:content;type:TEXT" json:"content"`
	LikeCount    int32  `gorm:"column:like_count;type:INTEGER" json:"like_count"`
	CollectCount int32  `gorm:"column:collect_count;type:INTEGER" json:"collect_count"`
	Scores       string `gorm:"column:scores;type:TEXT" json:"scores"`
	CreatedAt    int32  `gorm:"column:created_at;type:INTEGER" json:"created_at"`
	UpdatedAt    int32  `gorm:"column:updated_at;type:INTEGER" json:"updated_at"`
	DeletedAt    int32  `gorm:"column:deleted_at;type:INTEGER" json:"deleted_at"`
}

// TableName Blog's table name
func (*Blog) TableName() string {
	return TableNameBlog
}
