// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	ID          int32  `gorm:"column:id;type:INTEGER" json:"id"`
	Name        string `gorm:"column:name;type:TEXT" json:"name"`
	Description string `gorm:"column:description;type:TEXT" json:"description"`
	CreatedAt   int32  `gorm:"column:created_at;type:INTEGER" json:"created_at"`
	UpdatedAt   int32  `gorm:"column:updated_at;type:INTEGER" json:"updated_at"`
	DeletedAt   int32  `gorm:"column:deleted_at;type:INTEGER" json:"deleted_at"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
