// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID        int32  `gorm:"column:id;type:INTEGER" json:"id"`
	BlogID    int32  `gorm:"column:blog_id;type:INTEGER" json:"blog_id"`
	VisitorID int32  `gorm:"column:visitor_id;type:INTEGER" json:"visitor_id"`
	ReplyID   int32  `gorm:"column:reply_id;type:INTEGER" json:"reply_id"`
	G         int32  `gorm:"column:g;type:INTEGER" json:"g"`
	Content   string `gorm:"column:content;type:TEXT" json:"content"`
	Approved  int32  `gorm:"column:approved;type:INTEGER" json:"approved"`
	CreatedAt int32  `gorm:"column:created_at;type:INTEGER" json:"created_at"`
	UpdatedAt int32  `gorm:"column:updated_at;type:INTEGER" json:"updated_at"`
	DeletedAt int32  `gorm:"column:deleted_at;type:INTEGER" json:"deleted_at"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
