name: Create and upload gd-blog-server docker image
on: [push]
jobs:
  build-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      - name: Build
        run: |
          go build -o server cmd/main/main.go
          echo ${{ secrets.CONFIG_DEV_YAML_BASE64 }} | base64 --decode > configs/dev.yaml
          docker build -t zou8944/gd-blog-server:latest .
      - name: Publish to docker hub
        run: |
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          docker push zou8944/gd-blog-server:latest
          docker logout
      - name: Trigger re configs server
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_ACCESS_TOKEN }}" \
            https://api.github.com/repos/zou8944/gd-server-configs/dispatches \
            -d '{"event_type":"re-deploy","client_payload":{"blog-server-success": true}}'